import 'package:flutter/material.dart';

class AppColors {
  // Font Colors
  static const Color colorPrimary = Color(0xFFFEAE01);
  static const Color colorSecondary = Color(0xFFFDF555);
  static const Color colorBlack = Color(0xFF000000);
  static const Color appColorAccent = Color(0xFF757575);
  static const Color fieldBackgroundColor = Color(0xFFF5F6FA);
  static const Color colorBackground = Color(0xFFF6F5F8);
  static const Color fontColorWhite = Colors.white;
  static const Color appColorDark = Color(0xff212121);
  static const Color fontColorDark = Color(0xFF403E1C);
  static const Color fontColorDarkLow = Color(0xFF303030);
  static const Color cardColorDark = Color(0xff464647);
  static const Color fontColorGray = Color(0xFF888888);
  static const Color fontColorLightGray = Color(0xFF9E9E9E);
  static const Color fontLabelGray = Color(0xFFA2A2A2);
  static const Color colorTransparent = Colors.transparent;
  static const Color colorDisableWidget = Color(0xFFD5D4D4);
  static const Color colorDisableWidgetWeb = Color(0xFFc7c7c7);
  static const Color colorIconOuter = Color(0xFF5A5A5A);
  static const Color colorImagePlaceholder = Color(0xFFD9D9D9);
  static const Color colorScaffoldBackground = Color(0xFFFFFFFF);
  static const Color appBarFontColour = Color(0xFF403E1C);
  static const Color colorContactUsSecondary = Color(0xFF9F6D00);
  static const Color scanQRBackgroundColor = Color(0xFF3A3B3E);
  static const Color chipSecondaryColor = Color(0xFF8E8E8E);
  static const Color colorSuccess = Colors.green;
  static const Color colorFailed = Colors.red;
  static const Color colorPending = Colors.orange;
  static const Color colorReviewing = Colors.amber;
  static const Color colorHover = Color(0xFF3e236e);
  static const Color textFieldPrefixColor = Color(0xFF221F20);
  static const Color appDialogTitleColor = Color(0xFF0E1923);
  static const Color appDialogDescriptionColor = Color(0xFF403E1C);
  static const Color buttonDarkColor = Color(0xFF232323);
  static const Color buttonDisableColor = Color(0xFFE7E7E7);
  static const Color buttonDisableTextColor = Color(0xFFABABAB);
  static const Color onBoardingButtonColor1 = Color(0xff1B1B1B);
  static const Color onBoardingButtonColor2 = Color(0xff232323);
  static const Color forgetPinTextColor = Color(0xff232323);
  static const Color pinBorderColor = Color(0xff888888);
  static const Color drawerDividerColor = Color(0xffEFEFEF);
  static const Color colorHintTextLabel = Color(0xFF9E9E9E);
  static const Color dividerTextColor = Color(0xFFC4C4C4);

  static const Color cardColorLightDark = Color(0xffF4F4F4);
  static const Color cardColorDarkBG = Color(0xffEDEDED);
  static const Color cardColorDarkBGGradient = Color(0xffFCFCFC);
  static const Color borderColor = Color(0xffEFEFEF);
  static const Color listCardDarkBG = Color(0xFFEEEEEE);
  static const Color lankaQRStoreName = Color(0xFFF2F2F2);
  static const Color paymentMethodButtonBorder = Color(0xFFED1C24);
  static const Color textHintColor = Color(0xFF686868);
  static const Color errorDescriptionColor = Color(0xFFFF473A);
  static const Color storeIdColor = Color(0xFFCC3804);
  static const Color notificationSummeryContainer = Color(0xFFF3F3F3);
  static const Color notificationSummeryFontColor = Color(0xFF4F4F4F);
  static const Color miniStatementCreditColor = Color(0xFF149F2A);
  static const Color miniStatementDebitColor = Color(0xFFD60F0F);
  static const Color dotIndicator = Color(0xFF5C5C5C);
  static const Color scanQRTitleColor = Color(0xFFF7F8FC);
  static const Color qrSummeryLabelColor = Color(0xFF454545);

  static const Color bankListBorderColor = Color(0xFFCACACA);
  static const Color dividerColor = Color(0xFFACACAC);
  static const Color calendarGrayColor = Color(0xFFA6A6A6);
  static const Color grayCircleColor = Color(0xFF484848);
  static const Color grayAvatarColor = Color(0xFF7E7E7E);
  static const Color eDocCardColor = Color(0xFFF6F6F6);
  static const Color active = Color(0xFF1EBB70);
  static const Color pending = Color(0xFFF8BE26);
  static const Color cancel = Color(0xFFED1C24);
}
